apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/opensearch/data
    type: DirectoryOrCreate
